### ISSUE TITLE
Running GloVeTfIdf.py

### ISSUE THREAD

**Issue by anjasopo** [YungRAW/PlagiarismChecker#3]
how to fix this, when i try to run GloVeTfIdf.py i got this

File "GloVeTfIdf.py", line 70, in <module>
    evaluator = EmbeddingSimilarityEvaluator(dev_dataloader)
TypeError: __init__() missing 2 required positional arguments: 'sentences2' and 'scores'

Thankyou before

**Comment by alphasaur666** [comment]
Hi anjasopo!

From the looks of it, the evaluator class got modified in the Sentence Transformers project.  Check it out here : https://github.com/UKPLab/sentence-transformers/blob/f207cf39e41d6cc1328d0e94bb08dae748a92914/sentence_transformers/evaluation/EmbeddingSimilarityEvaluator.py#L12

You need to replace lines 68, 69, 70 and 88 with the new evaluator parameters, something like:
`evaluator = EmbeddingSimilarityEvaluator.from_input_examples(sts_reader.get_examples('sts-dev.csv'))`.
 Also, did you verify that you have both glove training txt file and wikipedia doc frequencies downloaded, alongside the dataset using get_data.py?

**Comment by anjasopo** [comment]
this issue solved with replacing lines 68,69,70 and 88
yes, I did. I'm done get the data
Thanks for your swift response @YungRAW

**Comment by alphasaur666** [comment]
Anytime anjasopo! Thanks for reporting the issue, I will make changes to the code right away.
